/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rca.v:1.1-15.10" *)
module rca(A, B, SUM);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "rca.v:2.31-2.32" *)
  wire _26_;
  (* src = "rca.v:2.31-2.32" *)
  wire _27_;
  (* src = "rca.v:2.31-2.32" *)
  wire _28_;
  (* src = "rca.v:2.31-2.32" *)
  wire _29_;
  (* src = "rca.v:2.31-2.32" *)
  wire _30_;
  (* src = "rca.v:2.31-2.32" *)
  wire _31_;
  (* src = "rca.v:2.31-2.32" *)
  wire _32_;
  (* src = "rca.v:2.31-2.32" *)
  wire _33_;
  (* src = "rca.v:3.31-3.32" *)
  wire _34_;
  (* src = "rca.v:3.31-3.32" *)
  wire _35_;
  (* src = "rca.v:3.31-3.32" *)
  wire _36_;
  (* src = "rca.v:3.31-3.32" *)
  wire _37_;
  (* src = "rca.v:3.31-3.32" *)
  wire _38_;
  (* src = "rca.v:3.31-3.32" *)
  wire _39_;
  (* src = "rca.v:3.31-3.32" *)
  wire _40_;
  (* src = "rca.v:3.31-3.32" *)
  wire _41_;
  (* src = "rca.v:4.31-4.34" *)
  wire _42_;
  (* src = "rca.v:4.31-4.34" *)
  wire _43_;
  (* src = "rca.v:4.31-4.34" *)
  wire _44_;
  (* src = "rca.v:4.31-4.34" *)
  wire _45_;
  (* src = "rca.v:4.31-4.34" *)
  wire _46_;
  (* src = "rca.v:4.31-4.34" *)
  wire _47_;
  (* src = "rca.v:4.31-4.34" *)
  wire _48_;
  (* src = "rca.v:4.31-4.34" *)
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  (* src = "rca.v:2.31-2.32" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "rca.v:3.31-3.32" *)
  input [7:0] B;
  wire [7:0] B;
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] C;
  (* src = "rca.v:4.31-4.34" *)
  output [7:0] SUM;
  wire [7:0] SUM;
  sky130_fd_sc_hs__and2_1 _64_ (
    .A(_34_),
    .B(_26_),
    .X(_50_)
  );
  sky130_fd_sc_hs__nor2_1 _65_ (
    .A(_34_),
    .B(_26_),
    .Y(_51_)
  );
  sky130_fd_sc_hs__nor2_1 _66_ (
    .A(_50_),
    .B(_51_),
    .Y(_42_)
  );
  sky130_fd_sc_hs__xnor2_1 _67_ (
    .A(_27_),
    .B(_50_),
    .Y(_52_)
  );
  sky130_fd_sc_hs__xnor2_1 _68_ (
    .A(_35_),
    .B(_52_),
    .Y(_43_)
  );
  sky130_fd_sc_hs__maj3_1 _69_ (
    .A(_27_),
    .B(_35_),
    .C(_50_),
    .X(_53_)
  );
  sky130_fd_sc_hs__xnor2_1 _70_ (
    .A(_28_),
    .B(_53_),
    .Y(_54_)
  );
  sky130_fd_sc_hs__xnor2_1 _71_ (
    .A(_36_),
    .B(_54_),
    .Y(_44_)
  );
  sky130_fd_sc_hs__maj3_1 _72_ (
    .A(_28_),
    .B(_36_),
    .C(_53_),
    .X(_55_)
  );
  sky130_fd_sc_hs__xnor2_1 _73_ (
    .A(_29_),
    .B(_55_),
    .Y(_56_)
  );
  sky130_fd_sc_hs__xnor2_1 _74_ (
    .A(_37_),
    .B(_56_),
    .Y(_45_)
  );
  sky130_fd_sc_hs__maj3_1 _75_ (
    .A(_29_),
    .B(_37_),
    .C(_55_),
    .X(_57_)
  );
  sky130_fd_sc_hs__xnor2_1 _76_ (
    .A(_30_),
    .B(_57_),
    .Y(_58_)
  );
  sky130_fd_sc_hs__xnor2_1 _77_ (
    .A(_38_),
    .B(_58_),
    .Y(_46_)
  );
  sky130_fd_sc_hs__maj3_1 _78_ (
    .A(_30_),
    .B(_38_),
    .C(_57_),
    .X(_59_)
  );
  sky130_fd_sc_hs__xnor2_1 _79_ (
    .A(_31_),
    .B(_59_),
    .Y(_60_)
  );
  sky130_fd_sc_hs__xnor2_1 _80_ (
    .A(_39_),
    .B(_60_),
    .Y(_47_)
  );
  sky130_fd_sc_hs__maj3_1 _81_ (
    .A(_31_),
    .B(_39_),
    .C(_59_),
    .X(_61_)
  );
  sky130_fd_sc_hs__xnor2_1 _82_ (
    .A(_32_),
    .B(_61_),
    .Y(_62_)
  );
  sky130_fd_sc_hs__xnor2_1 _83_ (
    .A(_40_),
    .B(_62_),
    .Y(_48_)
  );
  sky130_fd_sc_hs__maj3_1 _84_ (
    .A(_32_),
    .B(_40_),
    .C(_61_),
    .X(_63_)
  );
  sky130_fd_sc_hs__xor3_1 _85_ (
    .A(_33_),
    .B(_41_),
    .C(_63_),
    .X(_49_)
  );
  assign C[0] = 1'h0;
  assign _34_ = B[0];
  assign _26_ = A[0];
  assign SUM[0] = _42_;
  assign _27_ = A[1];
  assign _35_ = B[1];
  assign SUM[1] = _43_;
  assign _28_ = A[2];
  assign _36_ = B[2];
  assign SUM[2] = _44_;
  assign _29_ = A[3];
  assign _37_ = B[3];
  assign SUM[3] = _45_;
  assign _30_ = A[4];
  assign _38_ = B[4];
  assign SUM[4] = _46_;
  assign _31_ = A[5];
  assign _39_ = B[5];
  assign SUM[5] = _47_;
  assign _32_ = A[6];
  assign _40_ = B[6];
  assign SUM[6] = _48_;
  assign _33_ = A[7];
  assign _41_ = B[7];
  assign SUM[7] = _49_;
endmodule
