/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "kogge.v:1.1-36.10" *)
module kogge(A, B, SUM);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _157_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _158_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _159_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _160_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _161_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _162_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _163_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _164_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _165_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _166_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _167_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _168_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _169_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _170_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _171_;
  (* src = "kogge.v:2.31-2.32" *)
  wire _172_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _173_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _174_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _175_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _176_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _177_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _178_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _179_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _180_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _181_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _182_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _183_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _184_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _185_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _186_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _187_;
  (* src = "kogge.v:3.31-3.32" *)
  wire _188_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _189_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _190_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _191_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _192_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _193_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _194_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _195_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _196_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _197_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _198_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _199_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _200_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _201_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _202_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _203_;
  (* src = "kogge.v:4.31-4.34" *)
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  (* src = "kogge.v:2.31-2.32" *)
  input [15:0] A;
  wire [15:0] A;
  (* src = "kogge.v:3.31-3.32" *)
  input [15:0] B;
  wire [15:0] B;
  (* src = "kogge.v:8.22-8.23" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] C;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [14:0] \G[0] ;
  (* unused_bits = "0 1" *)
  wire [1:0] \G[1] ;
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] \G[2] ;
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \G[3] ;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [14:0] \G[4] ;
  (* src = "kogge.v:7.22-7.23" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] \P[0] ;
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [14:0] \P[1] ;
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14" *)
  wire [14:0] \P[2] ;
  (* src = "kogge.v:7.22-7.23" *)
  (* unused_bits = "8 9 10 11 12 13 14" *)
  wire [15:0] \P[3] ;
  (* src = "kogge.v:7.22-7.23" *)
  wire [15:0] \P[4] ;
  (* src = "kogge.v:4.31-4.34" *)
  output [15:0] SUM;
  wire [15:0] SUM;
  sky130_fd_sc_hs__and2_1 _236_ (
    .A(_173_),
    .B(_157_),
    .X(_205_)
  );
  sky130_fd_sc_hs__nor2_1 _237_ (
    .A(_173_),
    .B(_157_),
    .Y(_206_)
  );
  sky130_fd_sc_hs__nor2_1 _238_ (
    .A(_205_),
    .B(_206_),
    .Y(_189_)
  );
  sky130_fd_sc_hs__xnor2_1 _239_ (
    .A(_180_),
    .B(_164_),
    .Y(_207_)
  );
  sky130_fd_sc_hs__xnor2_1 _240_ (
    .A(_205_),
    .B(_207_),
    .Y(_196_)
  );
  sky130_fd_sc_hs__maj3_1 _241_ (
    .A(_180_),
    .B(_164_),
    .C(_205_),
    .X(_208_)
  );
  sky130_fd_sc_hs__xnor2_1 _242_ (
    .A(_181_),
    .B(_165_),
    .Y(_209_)
  );
  sky130_fd_sc_hs__xnor2_1 _243_ (
    .A(_208_),
    .B(_209_),
    .Y(_197_)
  );
  sky130_fd_sc_hs__maj3_1 _244_ (
    .A(_181_),
    .B(_165_),
    .C(_208_),
    .X(_210_)
  );
  sky130_fd_sc_hs__xnor2_1 _245_ (
    .A(_182_),
    .B(_166_),
    .Y(_211_)
  );
  sky130_fd_sc_hs__xnor2_1 _246_ (
    .A(_210_),
    .B(_211_),
    .Y(_198_)
  );
  sky130_fd_sc_hs__maj3_1 _247_ (
    .A(_182_),
    .B(_166_),
    .C(_210_),
    .X(_212_)
  );
  sky130_fd_sc_hs__xnor2_1 _248_ (
    .A(_183_),
    .B(_167_),
    .Y(_213_)
  );
  sky130_fd_sc_hs__xnor2_1 _249_ (
    .A(_212_),
    .B(_213_),
    .Y(_199_)
  );
  sky130_fd_sc_hs__maj3_1 _250_ (
    .A(_183_),
    .B(_167_),
    .C(_212_),
    .X(_214_)
  );
  sky130_fd_sc_hs__xnor2_1 _251_ (
    .A(_184_),
    .B(_168_),
    .Y(_215_)
  );
  sky130_fd_sc_hs__xnor2_1 _252_ (
    .A(_214_),
    .B(_215_),
    .Y(_200_)
  );
  sky130_fd_sc_hs__maj3_1 _253_ (
    .A(_184_),
    .B(_168_),
    .C(_214_),
    .X(_216_)
  );
  sky130_fd_sc_hs__xnor2_1 _254_ (
    .A(_185_),
    .B(_169_),
    .Y(_217_)
  );
  sky130_fd_sc_hs__xnor2_1 _255_ (
    .A(_216_),
    .B(_217_),
    .Y(_201_)
  );
  sky130_fd_sc_hs__maj3_1 _256_ (
    .A(_185_),
    .B(_169_),
    .C(_216_),
    .X(_218_)
  );
  sky130_fd_sc_hs__xnor2_1 _257_ (
    .A(_186_),
    .B(_170_),
    .Y(_219_)
  );
  sky130_fd_sc_hs__xnor2_1 _258_ (
    .A(_218_),
    .B(_219_),
    .Y(_202_)
  );
  sky130_fd_sc_hs__xnor2_1 _259_ (
    .A(_187_),
    .B(_171_),
    .Y(_220_)
  );
  sky130_fd_sc_hs__maj3_1 _260_ (
    .A(_186_),
    .B(_170_),
    .C(_218_),
    .X(_221_)
  );
  sky130_fd_sc_hs__xnor2_1 _261_ (
    .A(_220_),
    .B(_221_),
    .Y(_203_)
  );
  sky130_fd_sc_hs__maj3_1 _262_ (
    .A(_187_),
    .B(_171_),
    .C(_221_),
    .X(_222_)
  );
  sky130_fd_sc_hs__xnor2_1 _263_ (
    .A(_188_),
    .B(_172_),
    .Y(_223_)
  );
  sky130_fd_sc_hs__xnor2_1 _264_ (
    .A(_222_),
    .B(_223_),
    .Y(_204_)
  );
  sky130_fd_sc_hs__maj3_1 _265_ (
    .A(_188_),
    .B(_172_),
    .C(_222_),
    .X(_224_)
  );
  sky130_fd_sc_hs__xnor2_1 _266_ (
    .A(_174_),
    .B(_158_),
    .Y(_225_)
  );
  sky130_fd_sc_hs__xnor2_1 _267_ (
    .A(_224_),
    .B(_225_),
    .Y(_190_)
  );
  sky130_fd_sc_hs__maj3_1 _268_ (
    .A(_174_),
    .B(_158_),
    .C(_224_),
    .X(_226_)
  );
  sky130_fd_sc_hs__xnor2_1 _269_ (
    .A(_175_),
    .B(_159_),
    .Y(_227_)
  );
  sky130_fd_sc_hs__xnor2_1 _270_ (
    .A(_226_),
    .B(_227_),
    .Y(_191_)
  );
  sky130_fd_sc_hs__maj3_1 _271_ (
    .A(_175_),
    .B(_159_),
    .C(_226_),
    .X(_228_)
  );
  sky130_fd_sc_hs__xnor2_1 _272_ (
    .A(_176_),
    .B(_160_),
    .Y(_229_)
  );
  sky130_fd_sc_hs__xnor2_1 _273_ (
    .A(_228_),
    .B(_229_),
    .Y(_192_)
  );
  sky130_fd_sc_hs__maj3_1 _274_ (
    .A(_176_),
    .B(_160_),
    .C(_228_),
    .X(_230_)
  );
  sky130_fd_sc_hs__xnor2_1 _275_ (
    .A(_177_),
    .B(_161_),
    .Y(_231_)
  );
  sky130_fd_sc_hs__xnor2_1 _276_ (
    .A(_230_),
    .B(_231_),
    .Y(_193_)
  );
  sky130_fd_sc_hs__maj3_1 _277_ (
    .A(_177_),
    .B(_161_),
    .C(_230_),
    .X(_232_)
  );
  sky130_fd_sc_hs__xnor2_1 _278_ (
    .A(_178_),
    .B(_162_),
    .Y(_233_)
  );
  sky130_fd_sc_hs__xnor2_1 _279_ (
    .A(_232_),
    .B(_233_),
    .Y(_194_)
  );
  sky130_fd_sc_hs__maj3_1 _280_ (
    .A(_178_),
    .B(_162_),
    .C(_232_),
    .X(_234_)
  );
  sky130_fd_sc_hs__xnor2_1 _281_ (
    .A(_179_),
    .B(_163_),
    .Y(_235_)
  );
  sky130_fd_sc_hs__xnor2_1 _282_ (
    .A(_234_),
    .B(_235_),
    .Y(_195_)
  );
  assign C[0] = 1'h0;
  assign \G[0] [0] = C[1];
  assign \G[1]  = C[2:1];
  assign \G[2]  = C[4:1];
  assign \G[3]  = C[8:1];
  assign \G[4]  = C[15:1];
  assign \P[0] [0] = SUM[0];
  assign \P[1] [1:0] = { 1'hx, SUM[0] };
  assign \P[2] [3:0] = { 3'hx, SUM[0] };
  assign { \P[3] [15], \P[3] [7:0] } = { 8'hxx, SUM[0] };
  assign \P[4]  = { 15'hxxxx, SUM[0] };
  assign _173_ = B[0];
  assign _157_ = A[0];
  assign SUM[0] = _189_;
  assign _180_ = B[1];
  assign _164_ = A[1];
  assign SUM[1] = _196_;
  assign _181_ = B[2];
  assign _165_ = A[2];
  assign SUM[2] = _197_;
  assign _182_ = B[3];
  assign _166_ = A[3];
  assign SUM[3] = _198_;
  assign _183_ = B[4];
  assign _167_ = A[4];
  assign SUM[4] = _199_;
  assign _184_ = B[5];
  assign _168_ = A[5];
  assign SUM[5] = _200_;
  assign _185_ = B[6];
  assign _169_ = A[6];
  assign SUM[6] = _201_;
  assign _186_ = B[7];
  assign _170_ = A[7];
  assign SUM[7] = _202_;
  assign _187_ = B[8];
  assign _171_ = A[8];
  assign SUM[8] = _203_;
  assign _188_ = B[9];
  assign _172_ = A[9];
  assign SUM[9] = _204_;
  assign _174_ = B[10];
  assign _158_ = A[10];
  assign SUM[10] = _190_;
  assign _175_ = B[11];
  assign _159_ = A[11];
  assign SUM[11] = _191_;
  assign _176_ = B[12];
  assign _160_ = A[12];
  assign SUM[12] = _192_;
  assign _177_ = B[13];
  assign _161_ = A[13];
  assign SUM[13] = _193_;
  assign _178_ = B[14];
  assign _162_ = A[14];
  assign SUM[14] = _194_;
  assign _179_ = B[15];
  assign _163_ = A[15];
  assign SUM[15] = _195_;
endmodule
