/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* src = "rca.v:4.1-12.10" *)
module full_adder(A, B, Cin, Sum, Cout);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "rca.v:5.12-5.13" *)
  input A;
  wire A;
  (* src = "rca.v:6.12-6.13" *)
  input B;
  wire B;
  (* src = "rca.v:7.12-7.15" *)
  input Cin;
  wire Cin;
  (* src = "rca.v:9.12-9.16" *)
  output Cout;
  wire Cout;
  (* src = "rca.v:8.12-8.15" *)
  output Sum;
  wire Sum;
  assign _0_ = ~(Cin ^ A);
  assign Sum = ~(_0_ ^ B);
  assign _1_ = Cin & A;
  assign _2_ = B & ~(_0_);
  assign Cout = _2_ | _1_;
endmodule

(* top =  1  *)
(* src = "rca.v:17.1-39.10" *)
module rca(A, B, SUM);
  (* src = "rca.v:18.25-18.26" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "rca.v:19.25-19.26" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "rca.v:23.16-23.17" *)
  (* unused_bits = "8" *)
  wire [8:0] C;
  (* src = "rca.v:20.25-20.28" *)
  output [7:0] SUM;
  wire [7:0] SUM;
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:30.16-30.79" *)
  full_adder fa0 (
    .A(A[0]),
    .B(B[0]),
    .Cin(1'h0),
    .Cout(C[1]),
    .Sum(SUM[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:31.16-31.79" *)
  full_adder fa1 (
    .A(A[1]),
    .B(B[1]),
    .Cin(C[1]),
    .Cout(C[2]),
    .Sum(SUM[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:32.16-32.79" *)
  full_adder fa2 (
    .A(A[2]),
    .B(B[2]),
    .Cin(C[2]),
    .Cout(C[3]),
    .Sum(SUM[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:33.16-33.79" *)
  full_adder fa3 (
    .A(A[3]),
    .B(B[3]),
    .Cin(C[3]),
    .Cout(C[4]),
    .Sum(SUM[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:34.16-34.79" *)
  full_adder fa4 (
    .A(A[4]),
    .B(B[4]),
    .Cin(C[4]),
    .Cout(C[5]),
    .Sum(SUM[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:35.16-35.79" *)
  full_adder fa5 (
    .A(A[5]),
    .B(B[5]),
    .Cin(C[5]),
    .Cout(C[6]),
    .Sum(SUM[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:36.16-36.79" *)
  full_adder fa6 (
    .A(A[6]),
    .B(B[6]),
    .Cin(C[6]),
    .Cout(C[7]),
    .Sum(SUM[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:37.16-37.79" *)
  full_adder fa7 (
    .A(A[7]),
    .B(B[7]),
    .Cin(C[7]),
    .Cout(C[8]),
    .Sum(SUM[7])
  );
  assign C[0] = 1'h0;
endmodule
