/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "csa.v:1.1-10.10" *)
module csa(A, B, C, Sum, Carry);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  (* src = "csa.v:2.19-2.20" *)
  wire _080_;
  (* src = "csa.v:2.19-2.20" *)
  wire _081_;
  (* src = "csa.v:2.19-2.20" *)
  wire _082_;
  (* src = "csa.v:2.19-2.20" *)
  wire _083_;
  (* src = "csa.v:2.19-2.20" *)
  wire _084_;
  (* src = "csa.v:2.19-2.20" *)
  wire _085_;
  (* src = "csa.v:2.19-2.20" *)
  wire _086_;
  (* src = "csa.v:2.19-2.20" *)
  wire _087_;
  (* src = "csa.v:2.19-2.20" *)
  wire _088_;
  (* src = "csa.v:2.19-2.20" *)
  wire _089_;
  (* src = "csa.v:2.19-2.20" *)
  wire _090_;
  (* src = "csa.v:2.19-2.20" *)
  wire _091_;
  (* src = "csa.v:2.19-2.20" *)
  wire _092_;
  (* src = "csa.v:2.19-2.20" *)
  wire _093_;
  (* src = "csa.v:2.19-2.20" *)
  wire _094_;
  (* src = "csa.v:2.19-2.20" *)
  wire _095_;
  (* src = "csa.v:3.19-3.20" *)
  wire _096_;
  (* src = "csa.v:3.19-3.20" *)
  wire _097_;
  (* src = "csa.v:3.19-3.20" *)
  wire _098_;
  (* src = "csa.v:3.19-3.20" *)
  wire _099_;
  (* src = "csa.v:3.19-3.20" *)
  wire _100_;
  (* src = "csa.v:3.19-3.20" *)
  wire _101_;
  (* src = "csa.v:3.19-3.20" *)
  wire _102_;
  (* src = "csa.v:3.19-3.20" *)
  wire _103_;
  (* src = "csa.v:3.19-3.20" *)
  wire _104_;
  (* src = "csa.v:3.19-3.20" *)
  wire _105_;
  (* src = "csa.v:3.19-3.20" *)
  wire _106_;
  (* src = "csa.v:3.19-3.20" *)
  wire _107_;
  (* src = "csa.v:3.19-3.20" *)
  wire _108_;
  (* src = "csa.v:3.19-3.20" *)
  wire _109_;
  (* src = "csa.v:3.19-3.20" *)
  wire _110_;
  (* src = "csa.v:3.19-3.20" *)
  wire _111_;
  (* src = "csa.v:4.19-4.20" *)
  wire _112_;
  (* src = "csa.v:4.19-4.20" *)
  wire _113_;
  (* src = "csa.v:4.19-4.20" *)
  wire _114_;
  (* src = "csa.v:4.19-4.20" *)
  wire _115_;
  (* src = "csa.v:4.19-4.20" *)
  wire _116_;
  (* src = "csa.v:4.19-4.20" *)
  wire _117_;
  (* src = "csa.v:4.19-4.20" *)
  wire _118_;
  (* src = "csa.v:4.19-4.20" *)
  wire _119_;
  (* src = "csa.v:4.19-4.20" *)
  wire _120_;
  (* src = "csa.v:4.19-4.20" *)
  wire _121_;
  (* src = "csa.v:4.19-4.20" *)
  wire _122_;
  (* src = "csa.v:4.19-4.20" *)
  wire _123_;
  (* src = "csa.v:4.19-4.20" *)
  wire _124_;
  (* src = "csa.v:4.19-4.20" *)
  wire _125_;
  (* src = "csa.v:4.19-4.20" *)
  wire _126_;
  (* src = "csa.v:4.19-4.20" *)
  wire _127_;
  (* src = "csa.v:6.19-6.24" *)
  wire _128_;
  (* src = "csa.v:6.19-6.24" *)
  wire _129_;
  (* src = "csa.v:6.19-6.24" *)
  wire _130_;
  (* src = "csa.v:6.19-6.24" *)
  wire _131_;
  (* src = "csa.v:6.19-6.24" *)
  wire _132_;
  (* src = "csa.v:6.19-6.24" *)
  wire _133_;
  (* src = "csa.v:6.19-6.24" *)
  wire _134_;
  (* src = "csa.v:6.19-6.24" *)
  wire _135_;
  (* src = "csa.v:6.19-6.24" *)
  wire _136_;
  (* src = "csa.v:6.19-6.24" *)
  wire _137_;
  (* src = "csa.v:6.19-6.24" *)
  wire _138_;
  (* src = "csa.v:6.19-6.24" *)
  wire _139_;
  (* src = "csa.v:6.19-6.24" *)
  wire _140_;
  (* src = "csa.v:6.19-6.24" *)
  wire _141_;
  (* src = "csa.v:6.19-6.24" *)
  wire _142_;
  (* src = "csa.v:6.19-6.24" *)
  wire _143_;
  (* src = "csa.v:5.19-5.22" *)
  wire _144_;
  (* src = "csa.v:5.19-5.22" *)
  wire _145_;
  (* src = "csa.v:5.19-5.22" *)
  wire _146_;
  (* src = "csa.v:5.19-5.22" *)
  wire _147_;
  (* src = "csa.v:5.19-5.22" *)
  wire _148_;
  (* src = "csa.v:5.19-5.22" *)
  wire _149_;
  (* src = "csa.v:5.19-5.22" *)
  wire _150_;
  (* src = "csa.v:5.19-5.22" *)
  wire _151_;
  (* src = "csa.v:5.19-5.22" *)
  wire _152_;
  (* src = "csa.v:5.19-5.22" *)
  wire _153_;
  (* src = "csa.v:5.19-5.22" *)
  wire _154_;
  (* src = "csa.v:5.19-5.22" *)
  wire _155_;
  (* src = "csa.v:5.19-5.22" *)
  wire _156_;
  (* src = "csa.v:5.19-5.22" *)
  wire _157_;
  (* src = "csa.v:5.19-5.22" *)
  wire _158_;
  (* src = "csa.v:5.19-5.22" *)
  wire _159_;
  (* src = "csa.v:2.19-2.20" *)
  input [15:0] A;
  wire [15:0] A;
  (* src = "csa.v:3.19-3.20" *)
  input [15:0] B;
  wire [15:0] B;
  (* src = "csa.v:4.19-4.20" *)
  input [15:0] C;
  wire [15:0] C;
  (* src = "csa.v:6.19-6.24" *)
  output [15:0] Carry;
  wire [15:0] Carry;
  (* src = "csa.v:5.19-5.22" *)
  output [15:0] Sum;
  wire [15:0] Sum;
  sky130_fd_sc_hs__xor3_1 _160_ (
    .A(_096_),
    .B(_080_),
    .C(_112_),
    .X(_144_)
  );
  sky130_fd_sc_hs__xor3_1 _161_ (
    .A(_103_),
    .B(_087_),
    .C(_119_),
    .X(_151_)
  );
  sky130_fd_sc_hs__xor3_1 _162_ (
    .A(_104_),
    .B(_088_),
    .C(_120_),
    .X(_152_)
  );
  sky130_fd_sc_hs__xor3_1 _163_ (
    .A(_105_),
    .B(_089_),
    .C(_121_),
    .X(_153_)
  );
  sky130_fd_sc_hs__xor3_1 _164_ (
    .A(_106_),
    .B(_090_),
    .C(_122_),
    .X(_154_)
  );
  sky130_fd_sc_hs__xor3_1 _165_ (
    .A(_107_),
    .B(_091_),
    .C(_123_),
    .X(_155_)
  );
  sky130_fd_sc_hs__xor3_1 _166_ (
    .A(_108_),
    .B(_092_),
    .C(_124_),
    .X(_156_)
  );
  sky130_fd_sc_hs__xor3_1 _167_ (
    .A(_109_),
    .B(_093_),
    .C(_125_),
    .X(_157_)
  );
  sky130_fd_sc_hs__xor3_1 _168_ (
    .A(_110_),
    .B(_094_),
    .C(_126_),
    .X(_158_)
  );
  sky130_fd_sc_hs__xor3_1 _169_ (
    .A(_111_),
    .B(_095_),
    .C(_127_),
    .X(_159_)
  );
  sky130_fd_sc_hs__xor3_1 _170_ (
    .A(_097_),
    .B(_081_),
    .C(_113_),
    .X(_145_)
  );
  sky130_fd_sc_hs__xor3_1 _171_ (
    .A(_098_),
    .B(_082_),
    .C(_114_),
    .X(_146_)
  );
  sky130_fd_sc_hs__xor3_1 _172_ (
    .A(_099_),
    .B(_083_),
    .C(_115_),
    .X(_147_)
  );
  sky130_fd_sc_hs__xor3_1 _173_ (
    .A(_100_),
    .B(_084_),
    .C(_116_),
    .X(_148_)
  );
  sky130_fd_sc_hs__xor3_1 _174_ (
    .A(_101_),
    .B(_085_),
    .C(_117_),
    .X(_149_)
  );
  sky130_fd_sc_hs__xor3_1 _175_ (
    .A(_102_),
    .B(_086_),
    .C(_118_),
    .X(_150_)
  );
  sky130_fd_sc_hs__maj3_1 _176_ (
    .A(_096_),
    .B(_080_),
    .C(_112_),
    .X(_128_)
  );
  sky130_fd_sc_hs__maj3_1 _177_ (
    .A(_103_),
    .B(_087_),
    .C(_119_),
    .X(_135_)
  );
  sky130_fd_sc_hs__maj3_1 _178_ (
    .A(_104_),
    .B(_088_),
    .C(_120_),
    .X(_136_)
  );
  sky130_fd_sc_hs__maj3_1 _179_ (
    .A(_105_),
    .B(_089_),
    .C(_121_),
    .X(_137_)
  );
  sky130_fd_sc_hs__maj3_1 _180_ (
    .A(_106_),
    .B(_090_),
    .C(_122_),
    .X(_138_)
  );
  sky130_fd_sc_hs__maj3_1 _181_ (
    .A(_107_),
    .B(_091_),
    .C(_123_),
    .X(_139_)
  );
  sky130_fd_sc_hs__maj3_1 _182_ (
    .A(_108_),
    .B(_092_),
    .C(_124_),
    .X(_140_)
  );
  sky130_fd_sc_hs__maj3_1 _183_ (
    .A(_109_),
    .B(_093_),
    .C(_125_),
    .X(_141_)
  );
  sky130_fd_sc_hs__maj3_1 _184_ (
    .A(_110_),
    .B(_094_),
    .C(_126_),
    .X(_142_)
  );
  sky130_fd_sc_hs__maj3_1 _185_ (
    .A(_111_),
    .B(_095_),
    .C(_127_),
    .X(_143_)
  );
  sky130_fd_sc_hs__maj3_1 _186_ (
    .A(_097_),
    .B(_081_),
    .C(_113_),
    .X(_129_)
  );
  sky130_fd_sc_hs__maj3_1 _187_ (
    .A(_098_),
    .B(_082_),
    .C(_114_),
    .X(_130_)
  );
  sky130_fd_sc_hs__maj3_1 _188_ (
    .A(_099_),
    .B(_083_),
    .C(_115_),
    .X(_131_)
  );
  sky130_fd_sc_hs__maj3_1 _189_ (
    .A(_100_),
    .B(_084_),
    .C(_116_),
    .X(_132_)
  );
  sky130_fd_sc_hs__maj3_1 _190_ (
    .A(_101_),
    .B(_085_),
    .C(_117_),
    .X(_133_)
  );
  sky130_fd_sc_hs__maj3_1 _191_ (
    .A(_102_),
    .B(_086_),
    .C(_118_),
    .X(_134_)
  );
  assign _096_ = B[0];
  assign _080_ = A[0];
  assign _112_ = C[0];
  assign Sum[0] = _144_;
  assign _103_ = B[1];
  assign _087_ = A[1];
  assign _119_ = C[1];
  assign Sum[1] = _151_;
  assign _104_ = B[2];
  assign _088_ = A[2];
  assign _120_ = C[2];
  assign Sum[2] = _152_;
  assign _105_ = B[3];
  assign _089_ = A[3];
  assign _121_ = C[3];
  assign Sum[3] = _153_;
  assign _106_ = B[4];
  assign _090_ = A[4];
  assign _122_ = C[4];
  assign Sum[4] = _154_;
  assign _107_ = B[5];
  assign _091_ = A[5];
  assign _123_ = C[5];
  assign Sum[5] = _155_;
  assign _108_ = B[6];
  assign _092_ = A[6];
  assign _124_ = C[6];
  assign Sum[6] = _156_;
  assign _109_ = B[7];
  assign _093_ = A[7];
  assign _125_ = C[7];
  assign Sum[7] = _157_;
  assign _110_ = B[8];
  assign _094_ = A[8];
  assign _126_ = C[8];
  assign Sum[8] = _158_;
  assign _111_ = B[9];
  assign _095_ = A[9];
  assign _127_ = C[9];
  assign Sum[9] = _159_;
  assign _097_ = B[10];
  assign _081_ = A[10];
  assign _113_ = C[10];
  assign Sum[10] = _145_;
  assign _098_ = B[11];
  assign _082_ = A[11];
  assign _114_ = C[11];
  assign Sum[11] = _146_;
  assign _099_ = B[12];
  assign _083_ = A[12];
  assign _115_ = C[12];
  assign Sum[12] = _147_;
  assign _100_ = B[13];
  assign _084_ = A[13];
  assign _116_ = C[13];
  assign Sum[13] = _148_;
  assign _101_ = B[14];
  assign _085_ = A[14];
  assign _117_ = C[14];
  assign Sum[14] = _149_;
  assign _102_ = B[15];
  assign _086_ = A[15];
  assign _118_ = C[15];
  assign Sum[15] = _150_;
  assign Carry[0] = _128_;
  assign Carry[1] = _135_;
  assign Carry[2] = _136_;
  assign Carry[3] = _137_;
  assign Carry[4] = _138_;
  assign Carry[5] = _139_;
  assign Carry[6] = _140_;
  assign Carry[7] = _141_;
  assign Carry[8] = _142_;
  assign Carry[9] = _143_;
  assign Carry[10] = _129_;
  assign Carry[11] = _130_;
  assign Carry[12] = _131_;
  assign Carry[13] = _132_;
  assign Carry[14] = _133_;
  assign Carry[15] = _134_;
endmodule
